# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: '%env(resolve:LOCATE)%'
    authentication_cookie_name: '%env(resolve:AUTHENTICATION_COOKIE_NAME)%'
    private_api_endpoint: '%env(resolve:PRIVATE_API_ENDPOINT)%'
    authentication_url: '%env(resolve:AUTHENTICATION_URL)%'
    token_lifetime: 1800
    braintree_environment: '%env(resolve:BRAINTREE_ENVIRONMENT)%'
    braintree_merchant_id: '%env(resolve:BRAINTREE_MERCHANT_ID)%'
    braintree_public_key: '%env(resolve:BRAINTREE_PUBLIC_KEY)%'
    braintree_private_key: '%env(resolve:BRAINTREE_PRIVATE_KEY)%'
    braintree_customer_id: '%env(resolve:BRAINTREE_CUSTOMER_ID)%'
    # This parameter defines the codes of the locales (languages) enabled in the application
    app_locales: afr|alb|apd|ara|arm|aze|baq|bel|ben|bos|bul|bur|cat|ceb|cym|
                cze|dut|eng|epo|est|fin|fre|geo|ger|gle|glg|gre|guj|hat|hau|
                heb|hin|hmn|hrv|hun|ibo|ice|ind|isl|ita|jav|jpn|kan|kat|kaz|
                khm|kor|lao|lat|lav|lit|lzh|mac|mal|mao|mar|may|mkd|mlg|mlt|
                mon|msa|nep|nld|nor|nya|pan|per|pol|por|ron|rum|rus|sin|slk|
                slv|som|sot|spa|srp|swa|swe|tai|tam|tel|tgk|tgl|tha|tur|ukr|
                urd|uzb|vie|yid|yor|zho|zul
    cookie_language: '%env(resolve:COOKIE_LANGUAGE)%'
    app_id: '%env(resolve:APP_ID)%'
    app_key: '%env(resolve:APP_KEY)%'
    roles_key: '%env(resolve:ROLES_KEY)%'
    roles_ttl: '%env(resolve:ROLES_TTL)%' #seconds
    private_finance_api_endpoint: '%env(resolve:PRIVATE_FINANCE_API_ENDPOINT)%'
    redis_dns: '%env(resolve:REDIS_DNS)%'
    redis_port: '%env(resolve:REDIS_PORT)%'
    redis_database: '%env(resolve:REDIS_DATABASE)%'
    #payeer
    payeer_account: '%env(resolve:PAYEER_ACCOUNT)%'
    payeer_api_id: '%env(resolve:PAYEER_API_ID)%'
    payeer_api_pass: '%env(resolve:PAYEER_API_PASS)%'
    cookie_domain: '%env(resolve:COOCKIE_DOMAIN)%'



services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true        # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Service,Event,Kernel.php,ApiKernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # Create an alias, so that - by default - if you type-hint SiteUpdateManager,
    # the site_update_manager.superadmin will be used
    #App\Service\Request: '@service.request'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Extension\InstanceOfExtension:
        class: App\Extension\InstanceOfExtension
        public: false
        tags:
          - { name: twig.extension }
    
    App\Event\TokenAuthSubscriber:
        class: App\Event\TokenAuthSubscriber
        public: true
        arguments: ["@service_container"]
        tags:
          - { name: kernel.event_subscriber }
    
    translation.loader.po:
        public: true
        autoconfigure: true
        autowire: true
        class: Symfony\Component\Translation\Loader\PoFileLoader
        tags:
            - { name: translation.loader, alias: po, domain: default, priority: 1  }
    
    translation.dumper.po:
        public: true
        autoconfigure: true
        autowire: true
        class: Symfony\Component\Translation\Dumper\PoFileDumper
        tags:
            - { name: translation.dumper, alias: po, domain: default, priority: 2  }

    service.token:
        public: true
        autoconfigure: true
        autowire: true
        class: App\Service\TokenService
        arguments: ["@service_container"]

    service.utillity.cpayeer:
        class: App\Service\Utillity\CPayeer
        public: true
        arguments: 
            $account: '%payeer_account%'
            $apiId: '%payeer_api_id%'
            $apiPass: '%payeer_api_pass%'
        
    service.utillity.payeer:
        class: App\Service\Utillity\Payeer
        public: true
        arguments: ["@service_container"]

    
            
