apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}-migrate
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "10"
    "dapp/watch-logs": "true"
spec:
  activeDeadlineSeconds: 600
  template:
    metadata:
      name: {{ .Chart.Name }}-migrate
    spec:
      restartPolicy: Never
      imagePullSecrets:
      - name: "registrysecret"
      containers:
      - name: migration
{{ tuple "php" . | include "dapp_container_image" | indent 8 }}
        args:
        - php bin/console doctrine:migrations:migrate
        command:
        - /bin/bash
        - -c
        - --
        workingDir: "/var/www"
        imagePullPolicy: Always
        env:
{{ tuple "php" . | include "dapp_container_env" | indent 8 }}
{{- include "app_envs" . | indent 8 }}
        volumeMounts:
        - name: backend-config
          mountPath: /etc/php/7.2/fpm/pool.d/www.conf
          subPath: www.conf
        - name: backend-config
          mountPath: /etc/php/7.2/mods-available/newrelic.ini
          subPath: newrelic.ini
      volumes:
      - name: backend-config
        configMap:
          name: finance-configmap

